# Generated by Django 3.0.8 on 2020-07-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_toDo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='item_todo',
        ),
    ]
